
<h1>Története</h1>
<p id="elso">A vállalatot 2003-ban alapította Martin Eberhard, JB Straubel, Marc Tarpenning és Ian Wright. Nevét a szerb származású amerikai feltalálóról, Nikola Tesláról kapta. </p>
<p>A vállalat első terméke a Tesla Roadster volt, ami 2008-ban került sorozatgyártásba. A Roadster egy teljes mértékben elektromos meghajtású sportautó. Forgalmazására a vállalat weboldalán keresztül és koncesszióban, a világ számos pontján kerül sor. Az oldal a Star Gate nevet kapta és az első 220 Roadster eladását jegyezte négy hónap alatt. </p>
<p>A 2008-ban és 2009-ben gyártott, körülbelül ezer járművet előre lefoglalták az amerikai ügyfelek, akik a márka első piacát képezték. Első európai bemutatkozása során, 2008. április 25. és 28. között Monacóban, a márka olyan hírességek érdeklődését is felkeltette, mint Albert monacói herceg, Damon Hill egykori Formula–1 bajnok, valamint Bono a U2 zenekar énekese. A Roadster európai forgalmazása – Limited Edition név alatt – 2009-ben kezdődött, egy limitált 250 darabos sorozattal. 2009. március 26-án jelent meg a cég második modellje a Tesla Model S, ami egy elektromos meghajtású szedán. 2011 októberéig a modellre 6500 előjegyzés érkezett, az autók kiszállítását 2012 júniusában kezdték meg. </p>
<p>2012. február 9-én mutatta be a cég harmadik modelljét, a Tesla Model X-et, ami egy crossover (SUV). Gyártásának elindítását 2013-ra tervezték, ám később 2014-re halasztották, hogy az új projekt előtt a vállalat nyereségessége megerősödjön, illetve hogy 2013-ban elérjék a kitűzött 20 000-es darabszámot a Model S-ből. Végül a cég meghaladta ezt a tervet: 2013-ban közel 22 500 Model S-t adtak el. </p>
<p>A Tesla Motors létrehozott egy divíziót Tesla Energie Group (TEG) néven, amelynek feladata a Tesla modellekben használt energia tároló egységek fejlesztése és gyártása, továbbá e technológia értékesítése olyan partnerek számára, mint a Daimler vagy a Toyota. </p>
<p>2013-ra a Tesla Motors azt tervezte, hogy összesen 21 000 autót állít elő. Ebben az évben a cég Hollandiában új üzemet létesített, ahonnan az európai piacot szándékoztak ellátni: céljuk az volt, hogy 2014 után évi 10 000 Tesla elektromos autót tudjanak eladni a kontinensen. A Tesla azt is tervbe vette, hogy két éven belül piacra lép új modelljével, a Tesla Model E-vel, ami mérsékeltebb árú, és így elérhetőbb elektromos autó lesz az átlagos jövedelmű családok számára is: a modellt 35 000 dolláros áron tervezték forgalmazni. (Az autó később a Model 3 nevet kapta, mert a Model E-t a Ford egy modeljére bejegyeztette.) </p>
<p>2013 őszén Elon Musk egy interjúban bejelentette, hogy a cég beszáll az automata, azaz vezető nélküli autók kifejlesztésére irányuló versenybe, és 2016-ig megalkotja saját modelljét. </p>
<p>2014-ben a Tesla Motors minden szabadalmát közzétette és lehetővé tette, hogy azokat bárki felhasználja. A lépés célja az volt, hogy a versenytársak minél nagyobb mértékben építsék be a vállalat által kifejlesztett megoldásokat saját termékeikbe, ezáltal ugyanis a Tesla megoldásai válnak meghatározóvá a piacon. </p>
<p>2015-ben a cég bejelentette, hogy a háztartási és ipari energiatárolás piacára is be kívánnak lépni Powerwall és Powerpack nevű termékeikkel. A Tesla által fejlesztett nagy kapacitású integrált lítiumion-akkumulátorok elsősorban a napelemekkel előállított energia helyben történő tárolására szolgálnak, akár teljesen önálló áramellátással rendelkező és központi elektromos hálózattól független háztartásokat és ipari létesítményeket létrehozva. Az akkumulátorok másik felhasználási lehetősége, hogy a már meglévő elektromos hálózattal integrálva biztosítsa a folyamatos áramellátást, egyfajta egész épületet ellátó szünetmentes tápegységként. Övék volt a világ másodikelekktromos autója. Az első elektromos autó a BMW-é volt. </p>
<p>Kibővülő profiljára tekintettel 2017 februárjában a cég elhagyta nevéből az autóiparra utaló „Motors” tagot. A változtatást követően a vállalat neve „Tesla” (hivatalosan „Tesla, Inc”) lett. </p>
<p>2017. július 28-án átadták az első 30 Model 3-at a tulajdonosaiknak (mind Tesla alkalmazott). Az autóra ekkor a Tesla 455 ezer előrendeléssel rendelkezett A vállalat 2018 júliusában jelentette be, hogy sikerült elérniük az eredetileg kitűzött termelési célt, a hetenkénti 5 000 autó legyártását. Európába 2019 februárjában érkeznek az első megrendelések, miután az illetékesek megadták rá az engedélyt. </p>
<script>
function changeColor(){
    var randomColor = Math.floor(Math.random()*16777215).toString(16);
    console.log(randomColor);
    document.getElementById("elso").style.backgroundColor = "#" + randomColor;
}
const elem = document.getElementById("elso");
elem.addEventListener("click", changeColor, false);
</script>
